// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/data.ts
var profile = {
  name: "Dilan Nicol\xE1s Sanabria Murcia",
  title: "Ingeniero de Sonido y Productor Musical",
  location: "Colombia",
  summary: "Ingeniero de Sonido con experiencia en producci\xF3n de eventos en vivo, operaci\xF3n de sistemas de audio profesional, grabaci\xF3n, edici\xF3n y optimizaci\xF3n de sistemas. Ha participado en conciertos, eventos corporativos y producciones audiovisuales, desempe\xF1\xE1ndose en FOH, monitores, Stage Management, soporte t\xE9cnico, ingenier\xEDa de grabaci\xF3n y coordinaci\xF3n.",
  website: "https://diilansanabria.lovable.app"
};
var contact = {
  email: "dnsanabria.ing.sonido@gmail.com",
  phone: "+57 313 345 4305",
  whatsapp: "https://wa.me/573133454305"
};
var services = [
  { title: "Producci\xF3n Musical", description: "Creaci\xF3n y desarrollo de proyectos musicales con visi\xF3n art\xEDstica y t\xE9cnica profesional." },
  { title: "Mezcla y Edici\xF3n de Audio", description: "Procesamiento, balanceo y refinamiento de audio para obtener un sonido profesional." },
  { title: "Grabaci\xF3n de Voces e Instrumentos", description: "Captura de audio con equipos de alta gama y t\xE9cnicas de microfon\xEDa avanzadas." },
  { title: "Optimizaci\xF3n de Sistemas", description: "Dise\xF1o y calibraci\xF3n de sistemas de audio para espacios profesionales." },
  { title: "Sonido en Vivo", description: "FOH y monitores para eventos en vivo, festivales y presentaciones corporativas." },
  { title: "Audio para Streaming y Podcast", description: "Configuraci\xF3n, grabaci\xF3n y post-producci\xF3n de audio para contenido digital." }
];
var experience = [
  {
    company: "Camale\xF3n Tech",
    role: "Ingeniero de Sonido | Por proyectos",
    period: "2026 \u2013 Presente",
    highlights: [
      "Producci\xF3n t\xE9cnica y operaci\xF3n de sistemas de audio para eventos corporativos.",
      "Configuraci\xF3n, montaje, transmisi\xF3n y soporte de sistemas audiovisuales.",
      "Eventos para Avianca, FedeTransCarga y otras organizaciones.",
      "Montajes en Corferias, auditorios y centros de convenciones."
    ]
  },
  {
    company: "Walter Silva",
    role: "Ingeniero de Soporte \u2013 Stage Manager",
    period: "2025 \u2013 Presente",
    highlights: [
      "Coordinaci\xF3n t\xE9cnica durante presentaciones en vivo.",
      "Configuraci\xF3n y operaci\xF3n de sistemas de audio para conciertos.",
      "Soporte t\xE9cnico en escenario y gesti\xF3n de cambios durante el espect\xE1culo.",
      "Movistar Arena, Plaza de Bol\xEDvar, Teatro Julio Mario Santo Domingo y otros escenarios de gran formato."
    ]
  },
  {
    company: "Lum\xEDnica",
    role: "Ingeniero de Sonido | Por proyectos",
    period: "2024 \u2013 Presente",
    highlights: [
      "Calibraci\xF3n y optimizaci\xF3n de sistemas de audio para eventos corporativos y espect\xE1culos.",
      "Montaje, operaci\xF3n y soporte t\xE9cnico de equipos de sonido profesional.",
      "Producciones con artistas como Ma\xEDa, Alejo Gonz\xE1lez y otros eventos de gran formato."
    ]
  },
  {
    company: "IMPAKTO",
    role: "Ingeniero de Sonido",
    period: "2024 \u2013 2025",
    highlights: [
      "Calibraci\xF3n y optimizaci\xF3n de sistemas de audio.",
      "Grabaci\xF3n en bloque, de voces e instrumentos.",
      "Operaci\xF3n de monitores y FOH."
    ]
  },
  {
    company: "AVL",
    role: "Ingeniero de Sonido",
    period: "2024 \u2013 2025",
    highlights: ["Calibraci\xF3n y optimizaci\xF3n de sistemas de audio.", "Grabaci\xF3n de voces e instrumentos.", "Streaming."]
  },
  {
    company: "01-8000-UNKNWN",
    role: "Cofundador",
    period: "Septiembre 2020 \u2013 a la fecha",
    highlights: ["Edici\xF3n, mezcla y mastering.", "Producci\xF3n musical de proyectos propios."]
  }
];
var projects = [
  {
    title: "EP Live Session \u2013 Penchy Castro",
    category: "Grabaci\xF3n multicanal",
    highlights: [
      "Asistencia t\xE9cnica en la grabaci\xF3n multicanal de la sesi\xF3n en vivo.",
      "Configuraci\xF3n y verificaci\xF3n de micr\xF3fonos, cableado y flujo de se\xF1al.",
      "Apoyo en la edici\xF3n y mezcla del material grabado."
    ]
  },
  {
    title: "El Pu\xF1al Live Session \u2013 Walter Silva",
    category: "Producci\xF3n audiovisual",
    highlights: [
      "Coordinaci\xF3n del escenario y apoyo log\xEDstico durante la producci\xF3n.",
      "Supervisi\xF3n del sistema de monitoreo para los m\xFAsicos.",
      "Asistencia t\xE9cnica al ingeniero de grabaci\xF3n y verificaci\xF3n del flujo operativo."
    ]
  },
  {
    title: "01-8000-UNKNWN",
    category: "Producci\xF3n musical",
    highlights: ["Cofundador del proyecto desde septiembre de 2020.", "Edici\xF3n, mezcla y mastering."]
  }
];
var certifications = [
  { title: "Avid Certified User \u2013 Pro Tools 101", detail: "Avid \xB7 2022" },
  { title: "Avid Certified User \u2013 Pro Tools 110", detail: "Avid \xB7 2022" },
  { title: "Avid Certified User \u2013 Sonnox Elite Plug-ins", detail: "CW \xB7 2024" },
  { title: "DANTE Certified (Nivel 1)", detail: "Audinate \xB7 2025" },
  { title: "DANTE Certified (Nivel 2)", detail: "EDMAFS \xB7 2026" }
];
var education = [
  { title: "Ingenier\xEDa de Sonido", detail: "Universidad de San Buenaventura" },
  { title: "Dise\xF1o y Optimizaci\xF3n de Sistemas de Sonido", detail: "Escuela de M\xFAsica y Audio Fernando Sor" }
];

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Perfil profesional",
  description: "Devuelve el perfil profesional p\xFAblico de Dilan Sanabria y sus datos de contacto.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ profile, contact }, null, 2) }],
    structuredContent: { profile, contact }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_services_default = defineTool2({
  name: "list_services",
  title: "Listar servicios",
  description: "Lista los servicios de ingenier\xEDa de sonido y producci\xF3n musical que ofrece Dilan Sanabria.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_experience_default = defineTool3({
  name: "list_experience",
  title: "Listar experiencia",
  description: "Lista la experiencia laboral de Dilan Sanabria: empresa, rol, periodo y logros.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experience, null, 2) }],
    structuredContent: { experience }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "Listar proyectos",
  description: "Lista los proyectos destacados del portafolio de Dilan Sanabria.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/list-credentials.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_credentials_default = defineTool5({
  name: "list_credentials",
  title: "Formaci\xF3n y certificaciones",
  description: "Lista la formaci\xF3n acad\xE9mica y las certificaciones t\xE9cnicas de Dilan Sanabria.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify({ education, certifications }, null, 2) }],
    structuredContent: { education, certifications }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dilan-sanabria-sound",
  title: "Dilan Sanabria Sound",
  version: "0.1.0",
  instructions: "Herramientas del portafolio p\xFAblico de Dilan Nicol\xE1s Sanabria Murcia, Ingeniero de Sonido y Productor Musical en Colombia. Usa `get_profile` para el perfil y contacto, `list_services` para servicios, `list_experience` para trayectoria laboral, `list_projects` para proyectos destacados y `list_credentials` para formaci\xF3n y certificaciones.",
  tools: [get_profile_default, list_services_default, list_experience_default, list_projects_default, list_credentials_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
